name = "Langur"
uuid = "bdaad21b-8dc3-4ec1-a70f-d92ba100c3c8"
authors = ["Kajetan Knopp"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
